apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: us-central1-docker.pkg.dev/encoded-metrics-401109/my-repository/node:v1
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-loadbalancer
spec:
  selector:
    app: nodejs-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
